twig:
    paths: ['%kernel.project_dir%/src/Resources/templates']
    debug: '%kernel.debug%'
    strict_variables: '%kernel.debug%'
    exception_controller: App\Controller\ExceptionController::show
